config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root             'static_pages#home'
  get 'faq'        => 'static_pages#faq'
  get 'kontakt'  => 'static_pages#kontakt'
  get 'impressum'  => 'static_pages#impressum'
  get 'formulare'  => 'static_pages#formulare'
  get 'netzwerk'  => 'static_pages#netzwerk'  
  get 'service'    => 'static_pages#service'
  get 'raumpool'    => 'static_pages#raumpool'
  get 'signup'     => 'users#new'
  get 'user_rooms' => 'users#show'
  get  'login'   => 'sessions#new'
  get 'rooms/:id' => 'rooms#show_room'
  get 'roomlist' => 'rooms#list_rooms'
  post   'login'   => 'sessions#create'
  post 'rooms/:id' => 'rooms#edit'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :rooms
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :rooms do
    collection do
      match 'suche' => 'rooms#index', via: [:get, :post], as: :suche
    end
  end

end

app/models/room.rb
class Room < ActiveRecord::Base

  belongs_to :user

  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  mount_uploader :picture2, PictureUploader
  mount_uploader :picture3, PictureUploader
  mount_uploader :picture4, PictureUploader
  
  validates :user_id, presence: true

  validates :name, presence: true
  validates :strasse, presence: true
  validates :nummer, presence: true,
                     length: { maximum: 10 }
  VALID_PLZ_REGEX = /\d\d\d\d\d/
  validates :plz, presence: true,
                  format: { with: VALID_PLZ_REGEX }
  validates :ort, presence: true
  validates :groesse, presence: true,
                      numericality: true
  validates :pers_anzahl, presence: true,
                          numericality: true
  validates :anbieter, presence: true
  validates :preis, presence: true
  validates :kontakt_name, presence: true
  validates :kontakt_email, presence: true
  validates :kontakt_telefon, presence: true
  validates :beschreibung, presence: true

#  validates :technik_mikro, inclusion: { in: [true, false] }
#  validates :technik_wlan, inclusion: { in: [true, false] }

# custom validations

  validate  :picture_size
  validate  :picture2_size
  validate  :picture3_size
  validate  :picture4_size

  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "Die Bildgrösse sollte kleiner als 5 MB sein.")
      end
    end

    def picture2_size
      if picture2.size > 5.megabytes
        errors.add(:picture2, "Die Bildgrösse sollte kleiner als 5 MB sein.")
      end
    end

    def picture3_size
      if picture3.size > 5.megabytes
        errors.add(:picture3, "Die Bildgrösse sollte kleiner als 5 MB sein.")
      end
    end

    def picture4_size
      if picture4.size > 5.megabytes
        errors.add(:picture4, "Die Bildgrösse sollte kleiner als 5 MB sein.")
      end
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

protect_from_forgery :except => :suche

  #before_action :logged_in_user, only: [:create, :destroy, :edit]
  before_action :correct_user,   only: :destroy

  def index
#    @rooms = Room.paginate(page: params[:page])  # per_page value is defined in application_controller
#    @q = Room.ransack(params[:q].try(:merge, m: 'or'))
    @q = Room.ransack(params[:q])
    @rooms = @q.result.paginate(page: params[:page])
    @count = @rooms.count
  end
  
  def show_room
    @room = Room.find(params[:id])
  end
 

  def suche_old
    @q = Room.ransack(params[:q])
    @rooms = @q.result.paginate(page: params[:page])
  end

  def suche
    index
    render :index
  end
  
  def list_rooms
    index
    render :indexlist
  end
  
  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      flash[:success] = "Ein neuer Raum wurde erstellt!"
      redirect_to root_url
    else
#      @rooms = current_user.rooms.paginate(page: params[:page])
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def edit
    if Room.exists?(id:params[:id])
      @room = Room.find(params[:id])
      @feed_items = current_user.rooms.paginate(page: params[:page])    
    else
      suche  
    end
  end
  
  def update
    @room = Room.find(params[:id])
    if @room.update_attributes(room_params)
      flash[:success] = "Die Daten wurden gespeichert."
    end
    redirect_to request.referrer || root_url
  end
  


  def destroy
    @room.destroy
    flash[:success] = "Ein Raum wurde entfernt!"
    redirect_to request.referrer || root_url
  end

  private

    def room_params
      params.require(:room).permit( :name, :strasse, :nummer, :plz, :ort, :groesse, :pers_anzahl, :preis, :anbieter, :kontakt_name, :kontakt_email, :kontakt_telefon, :beschreibung,
        :mrbs_link, :weblink,
        :lage_eingang, :lage_garten, :lage_mvv, :lage_parkplatz, :anm_lage,
        :ausstattung_buehne, :ausstattung_dunkel, :ausstattung_klavier, :moebel_entfernbar, :anzahl_stuehle, :anzahl_tische, :anm_ausstattung,
        :technik_disko, :technik_mikro, :technik_projektion, :technik_wlan, :anm_technik,
        :verpflegung_catering, :verpflegung_gastro, :verpflegung_selbst, :verpflegung_teekueche, :anm_verpflegung,
        :zielgruppe_barrierefrei, :zielgruppe_kinder, :zielgruppe_party, :zielgruppe_seminar, :anm_zielgruppe,
        :bestuhlungsplan, :grundriss, :nutzungsvertrag, :anm_dokumente,
        :picture, :picture2, :picture3, :picture4, :anm_bilder,
        )
    end

    def correct_user
      @room = current_user.rooms.find_by(id: params[:id])
      redirect_to root_url if @room.nil?
    end

end

app/helpers/rooms_helper.rb
module RoomsHelper
  
    # Returns the Gravatar for the given room.
  def room_gravatar_for(room, options = { size: 80 })
    #gravatar_name = room.name
    size = options[:size]
#    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
#    image_tag(gravatar_url, alt: user.name, class: "gravatar")
     if room.picture.size != 0
       image_tag( room.picture, class: "gravatar", size: '40x40', alt: room.name )
     else
       image_tag( 'raumpool_logo_klein.jpg', class: "gravatar", size: '40x40' )
     end
  end
  
  
end

app/views/rooms/_room.html.erb
<li id="room-<%= room.id %>">

  <%# param 1: Text/Anzeige, param 2: Link-Url %> 
  <%= link_to room_gravatar_for(room, size: 50), room %>
  <span class="fett"><%= link_to room.name, room %></span>
  <span>(<%= room.groesse %> m²)</span>
  <span><% if room.anbieter %>(<%= room.anbieter %>)<% end %></span>
  <span><%= room.strasse %></span>
  <span><%= room.nummer %></span>,
  <span><%= room.plz %></span>
  <span><%= room.ort %></span>,
  <span>Tel. <%= room.kontakt_telefon %></span>,
  <span><%= room.kontakt_email %></span>

  
  <% if room.beschreibung %>
  <div class="beschreibung">
    <%= truncate( room.beschreibung, :length => 80 ) %>
    <%# image_tag room.picture.url if room.picture? %>
  </div>
  <% end %>
 
  <span class="timestamp">
    Erstellt <%= time_ago_in_words(room.created_at) %>.
    <% if current_user?(room.user) %>
      <%= link_to "löschen", room, method: :delete, data: { confirm: "Sicher?" } %>
      | <%= link_to "editieren", room, method: :edit %>
    <% end %>
  </span>

</li>

app/views/rooms/edit.html.erb
<% if logged_in? %>
<div class="row">
  <aside id="col-md-4" style="width:33.3%;float:left;">
  	<!--
    <section class="user_info">
      <h1>
        <%#= gravatar_for @user %>
        <%#= @user.name %>
      </h1>
    </section>
-->
    <section class="room_form">
        <%= render 'shared/room_form' %>     
    </section>  	
  </aside>
  <div class="col-md-8" style="width:66.7%;float:right;">
    <h3>Meine Räume <span>( <%= pluralize(current_user.rooms.count,'') %>)</span></h3>
    <ol class="rooms">
    	<%= render @feed_items %>
    </ol>
  </div>
</div>
<% end %>

app/views/rooms/index.html.erb
<% provide(:title, 'Räume') %>
<h1>Räume ( <%= @rooms.count %> )</h1>

<% content_for :search do %>
<%= search_form_for @q, url: suche_rooms_path, method: :post do |f| %>
<h2>Raumsuche</h2>
<div id="search_container">
  <div class="center_col" id="simple_search">
    <%= f.label :name_or_beschreibung_or_strasse, 'Raumname oder Beschreibung enthält' %>
    <%= f.text_field :name_or_beschreibung_or_strasse_cont, placeholder: 'Stichwort' %>
    <%# f.label :strasse, 'Strasse enthält' %>
    <%# f.text_field :strasse_cont, placeholder: 'Strasse' %>
    <%= f.label 'Grösse mind. (m²)' %>
    <%= f.text_field :groesse_gteq, placeholder: 'Grösse von' %>
    <%# f.label 'Grösse max. (m²)' %>
    <%# f.text_field :groesse_lteq, placeholder: 'Grösse bis' %>
    <%= f.label :pers_anzahl, 'Anzahl Personen (mind.)' %>
    <%= f.text_field :pers_anzahl_gteq, placeholder: 'Personenanzahl von' %>
  </div>

  <div class="right_col" id="extended_search" style="text-align:left;">
  
    <div class="subheader">Lage</div>
<table class="table borderless">
<tr><td><%= f.label :lage_eingang, 'Eigener Eingang' %></td><td><%= f.check_box :lage_eingang_true, include_hidden: false %></td>
<td class="searchdesc"><%= f.label :lage_garten, 'mit Zugang zu Garten oder Park'%></td><td><%= f.check_box :lage_garten_true, include_hidden: false %></td></tr>
<tr><td><%= f.label :lage_mvv, 'Öffentlich erreichbar' %></td><td><%= f.check_box :lage_mvv_true, include_hidden: false %></td>
<td class="searchdesc"><%= f.label :lage_parkplatz, 'Parkplatzfreundlich' %></td><td><%= f.check_box :lage_parkplatz_true, include_hidden: false %></td></tr>
</table>

    <div class="subheader">Raumausstattung</div>
<table border="0" class="searchtable">
<tr><td><%= f.label :ausstattung_dunkel, 'Abdunklung möglich' %></td><td><%= f.check_box :ausstattung_dunkel_true, include_hidden: false %></td>
<td class="searchdesc"><%= f.label :ausstattung_buehne, 'mit Bühne' %></td><td><%= f.check_box :ausstattung_buehne_true, include_hidden: false %></td></tr>
<tr><td><%= f.label :ausstattung_klavier, 'mit Klavier' %></td><td><%= f.check_box :ausstattung_klavier_true, include_hidden: false %></td>
<td class="searchdesc"><%= f.label :moebel_entfernbar, 'Stühle / Tische entfernbar' %></td><td><%= f.check_box :moebel_entfernbar_true, include_hidden: false %></td></tr>
</table>

    <div class="subheader">Technische Ausstattung</div>
<table border="0" class="searchtable">
<tr><td><%= f.label :technik_disko, 'mit Diskoanlage' %></td><td><%= f.check_box :technik_disko_true, include_hidden: false %></td>
<td class="searchdesc"><%= f.label :technik_mikro, 'Mikrofon verfügbar' %></td><td><%= f.check_box :technik_mikro_true, include_hidden: false %></td></tr>
<tr><td><%= f.label :technik_projektion, 'mit Projektionsmöglichkeit / Beamer' %></td><td><%= f.check_box :technik_projektion_true, include_hidden: false %></td>
<td class="searchdesc">    <%= f.label :technik_wlan, 'Wlan verfügbar' %></td><td><%= f.check_box :technik_wlan_true, include_hidden: false %></td></tr>
</table>
 
    <div class="subheader">Versorgungsmöglichkeiten</div>
<table border="0" class="searchtable">
<tr><td><%= f.label :verpflegung_catering, 'Catering verfügbar' %></td><td><%= f.check_box :verpflegung_catering_true, include_hidden: false %></td>
<td class="searchdesc"><%= f.label :verpflegung_gastro, 'Gastronomie in der Nähe' %></td><td><%= f.check_box :verpflegung_gastro_true, include_hidden: false %></td></tr>
<tr><td><%= f.label :verpflegung_selbst, 'Selbstversorgung (Küche)' %></td><td><%= f.check_box :verpflegung_selbst_true, include_hidden: false %></td>
<td class="searchdesc"><%= f.label :verpflegung_teekueche, 'mit Teeküche' %></td><td><%= f.check_box :verpflegung_teekueche_true, include_hidden: false %></td></tr>
</table>

    <div class="subheader">Zielgruppe</div>
<table border="0" class="searchtable">
<tr><td><%= f.label :zielgruppe_barrierefrei, 'Barrierefrei' %></td><td><%= f.check_box :zielgruppe_barrierefrei_true, include_hidden: false %></td>
<td class="searchdesc"><%= f.label :zielgruppe_kinder, 'Kinderfreundlich' %></td><td><%= f.check_box :zielgruppe_kinder_true, include_hidden: false %></td></tr>
<tr><td><%= f.label :zielgruppe_party, 'Partytauglich' %></td><td><%= f.check_box :zielgruppe_party_true, include_hidden: false %></td>
<td class="searchdesc"><%= f.label :zielgruppe_seminar, 'Seminargeeignet' %></td><td><%= f.check_box :zielgruppe_seminar_true, include_hidden: false %></td></tr>
</table>

  </div>  <!-- right_col -->
  <div id="extended_search_link" onclick="toggle_extended_search();">Erweiterte Suche</div>
</div>
 
<h2><%= f.submit 'Suchen', class: 'btn btn-primary', id: 'rooms_search_button' %></h2>
<% end %>  <!-- search_form_for -->

  <div style="clear:both;"></div>
<!--
  <h4>Sortiere Räume nach:</h4>
  <%= sort_link @q, :name, "Raumname" %> |
  <%= sort_link @q, :strasse, "Strasse" %> |
  <%= sort_link @q, :groesse, "Grösse" %>
-->
<% end %>

  <div id"rooms_list">
  <ul class="rooms"><%= render @rooms %></ul>
  </div>
  <div style="clear:both;"><%= will_paginate %></div>

app/views/rooms/indexlist.html.erb
<% provide(:title, 'Räume') %>
<h1>Räume ( <%= @rooms.count %> )</h1>

<div id"rooms_list">
	<ul class="rooms"><%= render @rooms %></ul>
</div>
<div style="clear:both;"><%= will_paginate %></div>

app/views/rooms/show.html.erb
<% provide(:title, @user.name, @room.name, @room.id) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        Räume
      </h1>
      <p>
        in der Messestadt
      </p>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.rooms.any? %>
      <h3>Räume ( <%= @user.rooms.count %> )</h3>
      <ol class="rooms">
        <%= render @rooms %>
      </ol>
      <%= will_paginate @rooms %>
    <% end %>
  </div>
</div>

app/views/rooms/show_room.html.erb
<div id="row">
  <aside id="col-md-4">
    <section id="room_info">
      <h1>
        <%= @room.name %> <% if @room.anbieter %>(<%= @room.anbieter %>)<% end %>        
      </h1>
      <div id="main_pic">
      	<%= image_tag(@room.picture) if @room.picture.size != 0 %>
      </div>
      <p class="room_address">
        <%= @room.strasse %> <%= @room.nummer %>, <%= @room.plz %> <%= @room.ort %>
        <% unless @room.weblink == nil or @room.weblink == "" %>&nbsp;&nbsp;&nbsp;&rarr; <%= link_to 'Homepage', @room.weblink, :target => '_blank' %><% end %>
        <% unless @room.mrbs_link == nil or @room.mrbs_link == "" %>&nbsp;&nbsp;&nbsp;&rarr; <%= link_to 'Belegungskalender', @room.mrbs_link, :target => '_blank' %><% end %>
      </p>
      <p class="room_contact gruen fett">
        Kontakt: <%= @room.kontakt_name %>, <%= @room.kontakt_telefon %>, <%= @room.kontakt_email %>
      </p>
      <p><%= @room.groesse %> m², bis zu <%= @room.pers_anzahl %> Personen, Preis: <%= @room.preis %></p>
      <p>
      	<span class="fett">Beschreibung:</span> 
      	<%= @room.beschreibung %>
      </p>

      <p class="fett">Weitere Infos:</p>

<div class="container-fluid">

<div class="row">

<div class="col-md-4">

<table class="room_desc_infos">
      	<tr>
      		<th colspan="3" style="width:30%;">Lage</th>
      		<th colspan="3">Technik</th>
      		<th colspan="3">Zielgruppe</th>      		
      	</tr>
      	<tr>
      		<td>Eigener Eingang</td><td><% if @room.lage_eingang == true %>Ja<% else %>Nein<% end %></td><td class="platzhalter">&nbsp;</td>
      		<td>Diskobeleuchtung</td><td><% if @room.technik_disko == true %>Ja<% else %>Nein<% end %></td><td class="platzhalter">&nbsp;</td>
      		<td>Barrierefrei</td><td><% if @room.zielgruppe_barrierefrei == true %>Ja<% else %>Nein<% end %></td><td class="platzhalter">&nbsp;</td>
      	</tr>	
      	<tr>	
      		<td>Garten- oder Park-Anbindung</td><td><% if @room.lage_garten == true %>Ja<% else %>Nein<% end %></td><td class="platzhalter">&nbsp;</td>
      		<td>Mikrophon</td><td><% if @room.technik_mikro == true %>Ja<% else %>Nein<% end %></td><td class="platzhalter">&nbsp;</td>
      		<td>Für Kinder geeignet</td><td><% if @room.zielgruppe_kinder == true %>Ja<% else %>Nein<% end %></td><td class="platzhalter">&nbsp;</td>
      	</tr>	
      	<tr>	
      		<td>Gute MVV-Anbindung</td><td><% if @room.lage_mvv == true %>Ja<% else %>Nein<% end %></td><td class="platzhalter">&nbsp;</td>
      		<td>Beamer</td><td><% if @room.technik_projektion == true %>Ja<% else %>Nein<% end %></td><td class="platzhalter">&nbsp;</td>
      		<td>Party-tauglich</td><td><% if @room.zielgruppe_party == true %>Ja<% else %>Nein<% end %></td><td class="platzhalter">&nbsp;</td>      		
      	</tr>
      	<tr>     		
      		<td>Gute Parkmöglichkeit</td><td><% if @room.lage_parkplatz == true %>Ja<% else %>Nein<% end %></td><td class="platzhalter">&nbsp;</td>
  			<td>WLan</td><td><% if @room.technik_wlan == true %>Ja<% else %>Nein<% end %></td><td class="platzhalter">&nbsp;</td>
      		<td>Seminar-geeignet</td><td><% if @room.zielgruppe_seminar == true %>Ja<% else %>Nein<% end %></td><td class="platzhalter">&nbsp;</td>
      	</tr>
		</table>
      	
      	
 		<table class="room_desc_infos">
 		<tr><td colspan="5">&nbsp;</tr>
      	<tr>
      		<th colspan="3">Verpflegung</th>
      		<th colspan="2" class="spaceleft">Ausstattung</th>
      	</tr>
      	<tr>
      		<td>Catering möglich</td><td><% if @room.verpflegung_catering == true %>Ja<% else %>Nein<% end %></td><td class="platzhalter">&nbsp;</td>
      		<td class="spaceleft">Bühne</td><td><% if @room.ausstattung_buehne == true %>Ja<% else %>Nein<% end %></td>
      	</tr>
      	<tr>
      		<td>Gastro-Betrieb nahebei</td><td><% if @room.verpflegung_gastro == true %>Ja<% else %>Nein<% end %></td><td class="platzhalter">&nbsp;</td>
      		<td class="spaceleft">Abdunkelbar</td><td><% if @room.ausstattung_dunkel == true %>Ja<% else %>Nein<% end %></td>
      	</tr>
      	<tr>
      		<td>Selbstverpflegung möglich</td><td><% if @room.verpflegung_selbst == true %>Ja<% else %>Nein<% end %></td><td class="platzhalter">&nbsp;</td>
      		<td class="spaceleft">Mit Klavier oder Keyboard</td><td><% if @room.ausstattung_klavier == true %>Ja<% else %>Nein<% end %></td>
      	</tr>
      	<tr>
      		<td>Teeküche vorhanden</td><td><% if @room.verpflegung_teekueche == true %>Ja<% else %>Nein<% end %></td><td class="platzhalter">&nbsp;</td>
      		<td class="spaceleft">Anzahl Tische/Stühle</td>
      		<td><% if @room.anzahl_tische || @room.anzahl_stuehle %>
      				<%= @room.anzahl_tische %> / <%= @room.anzahl_stuehle %>
      				<% if @room.moebel_entfernbar == true %>(entfernbar)<% else %>(nicht entfernbar)<% end %>
      				<% else %>0 / 0<% end %>
      		</td>
      	</tr>
		</table>
</div>      	
      	<table class="room_anm_infos">
      	<% if @room.anm_lage || @room.anm_technik || @room.anm_zielgruppe || @room.anm_ausstattung || @room.anm_verpflegung %>
      	<tr><td colspan="2">&nbsp;</tr>
      		<tr><th colspan="2">Anmerkung</th></tr>
      	<% end %>
      		
      	<% if @room.anm_lage %><tr><td>Lage:</td><td class="longtext"><%= @room.anm_lage %></td></tr><% end %>
      	<% if @room.anm_technik %><tr><td>Technik:</td><td class="longtext"><%= @room.anm_technik %></td></tr><% end %>
      	<% if @room.anm_zielgruppe %><tr><td>Zielgruppe:</td><td class="longtext"><%= @room.anm_zielgruppe %></td></tr><% end %>
      	<% if @room.anm_ausstattung %><tr><td>Ausstattung:</td><td class="longtext"><%= @room.anm_ausstattung %></td></tr><% end %>
      	<% if @room.anm_verpflegung %><tr><td>Verpflegung:</td><td class="longtext"><%= @room.anm_verpflegung %></td></tr><% end %>
		<% if @room.anm_dokumente %><tr><td>Dokumente:</td><td class="longtext"><%= @room.anm_dokumente %></td></tr><% end %>
		<% if @room.anm_bilder %><tr><td>Bilder:</td><td class="longtext"><%= @room.anm_bilder %></td></tr><% end %>   

		<tr><td colspan="2">&nbsp;</tr>
		<tr>
			<td><b>Dokumente / Nutzungsverträge:</b></td>
			<td><% unless @room.nutzungsvertrag == "" or @room.nutzungsvertrag == nil %><%= link_to "Nutzungsvertrag (pdf, download)", @room.nutzungsvertrag if @room.nutzungsvertrag =~ /pdf/ %><% else %>noch nicht vorhanden<% end %></td>
		</tr>
		</table>





</div>
</div>

    
      
    <% if @room.picture2.size != 0 || @room.picture3.size != 0 || @room.picture4.size != 0 %>
      <h3>Weitere Bilder</h3>
      <div id="room_pics">
       <%= image_tag(@room.picture2) if @room.picture2.size != 0 %>
       <%= image_tag(@room.picture3) if @room.picture3.size != 0 %>
       <%= image_tag(@room.picture4) if @room.picture4.size != 0 %>
      </div>
    <% end %>
      
 

    </section>
  </aside>
</div>

<!--


      t.string :bestuhlungsplan
      t.string :grundriss
      
      t.text   :anm_dokumente
      
      t.string :picture
      t.text   :anm_bilder
-->