config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root             'static_pages#home'
  get 'faq'        => 'static_pages#faq'
  get 'kontakt'  => 'static_pages#kontakt'
  get 'impressum'  => 'static_pages#impressum'
  get 'formulare'  => 'static_pages#formulare'
  get 'netzwerk'  => 'static_pages#netzwerk'  
  get 'service'    => 'static_pages#service'
  get 'raumpool'    => 'static_pages#raumpool'
  get 'signup'     => 'users#new'
  get 'user_rooms' => 'users#show'
  get  'login'   => 'sessions#new'
  get 'rooms/:id' => 'rooms#show_room'
  get 'roomlist' => 'rooms#list_rooms'
  post   'login'   => 'sessions#create'
  post 'rooms/:id' => 'rooms#edit'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :rooms
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :rooms do
    collection do
      match 'suche' => 'rooms#index', via: [:get, :post], as: :suche
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <ul>
      <li><%= link_to "Über den Raumpool", raumpool_path %></li>
      <li><%= link_to "Netzwerk", netzwerk_path %></li>      
      <li><%= link_to "Kontakt", kontakt_path %></li>
      <li><%= link_to "Impressum", impressum_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <%= link_to image_tag( 'raumpool_logo_klein.jpg', alt: 'logo', height: 30 ), root_path, id: "logo" %>
    <%# link_to "raumpool", root_path, id: "logo" %>
        
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <a class="navbar-brand" href="/">Raumpool</a>
    </div>

    <div class="navbar-collapse collapse">
    
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Raumliste', roomlist_path %></li>
        <li><%= link_to 'Raumsuche', rooms_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Service <b class="caret"></b>
          </a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Formulare', formulare_path %></li>
          <li><%= link_to 'FAQ', faq_path %></li>
        </ul>
        </li>
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Mein Raumpool <b class="caret"></b>
          </a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Raum erstellen', root_path %></li>
          <li><%= link_to 'Meine Räume', current_user %></li>
          <li class="divider"></li>
          <li><%= link_to 'Mein Profil', edit_user_path(current_user) %></li>
            <% if current_user.admin? %>
              <li><%= link_to 'Benutzerliste', users_path %></li>
            <% end %>
          <li class="divider"></li>
          <li><%= link_to 'Abmelden', logout_path, method: "delete" %></li>
        </ul>
        </li>
        <% else %>
          <li><%= link_to 'Anmelden', login_path %></li>
        <% end %>            
      </ul>

    </div><!-- navbar-collapse -->
  </div><!-- container -->

</div><!-- navbar -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="description" content="Hier können Sie Räume in der Messestadt München für diverse Zwecke finden oder anbieten.">
  <meta name="keywords" content="raumpool, messestadt, riem, münchen, munich, germany, deutschland, raum, räume, zimmer, rooms, rent, feier, feiern, party, vermietung, vermieten, mieten, raumsuche, raumliste, messe, icm, gästeappartements">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%# javascript_include_tag 'jquery-2.2.0.min.js', 'application' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield( :search ) %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>